
server:
  port: 8081

spring:
  application:
    name: prometheus-example # \u670D\u52A1\u540D

management:
  context-path: /actuator  # \u8BBF\u95EEURL\u8981\u52A0\u4E0A\u6B64\u524D\u7F00,\u5982 http://localhost:8081/actuator/prometheus
  security:
    enabled: false  #\u30001.5\u9ED8\u8BA4\u5BF9 management \u63A5\u53E3\u52A0\u4E86\u5B89\u5168\u63A7\u5236\uFF0C\u9700\u8981\u5173\u95ED
  endpoints:
    web:
      exposure:
        include: "*"  # \u8868\u793A\u6240\u6709\u7684\u6307\u6807\u90FD\u4F1A\u4E0A\u62A5
  metrics:
    tags:
      application: ${spring.application.name} # \u589E\u52A0\u6BCF\u4E2A\u6307\u6807\u7684\u5168\u5C40\u7684tag\uFF0C\u53CA\u7ED9\u6BCF\u4E2A\u6307\u6807\u4E00\u4E2A application\u7684 tag,\u503C\u662F spring.application.name\u7684\u503C
    export:
      prometheus:
        enabled: true  # \u542F\u7528 prometheus \u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u5C31\u662Ftrue
  port: 1001 # \u7BA1\u7406\u7AEF\u53E3,2.X\u6BD41.X\u591A\u4E2Asever\u524D\u7F00

## eureka client\u914D\u7F6E
eureka:
  client:
    register-with-eureka: true # \u5C06\u81EA\u5DF1\u6CE8\u518C\u8FDBEureka Server,\u9ED8\u8BA4\u662Ftrue
    fetch-registry: true  # \u4ECEEureka Server\u62C9\u53D6\u5DF2\u6709\u7684\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u662Ftrue
    service-url:
      defaultZone: http://localhost:8010/eureka


